// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eydrcpkszdyrjtozuprb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZHJjcGtzemR5cmp0b3p1cHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDc1NDksImV4cCI6MjA1OTcyMzU0OX0.nFeEWwPUcBQeX3YOL8pz76e7If7DDHYbmzgeFdqupeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);